services:

  standalone:
    build:
      context: .
      dockerfile: infra/Dockerfile.standalone
    ports:
      - 8080:3000
    env_file:
      - .env
    environment:
      - DATABASE_URL=/app/data/ping-status.db
    volumes:
      - ./data:/app/data