services:

  standalone:
    build:
      context: .
      dockerfile: infra/Dockerfile.standalone
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - PORT=8080
      - DATABASE_PATH=/app/data/ping-status.db
    volumes:
      - ./data:/app/data